// src/services/live/session.service.js
// UC-LIVE-01 (Create/Schedule) | UC-LIVE-02 (Edit/Cancel) | UC-LIVE-03 (View Schedule)
// UC-LIVE-08 (End & Process Recording)

const LiveSession = require('../../models/liveSession.model');
const CourseUnit = require('../../models/CourseUnit');
const Course = require('../../models/Course');
const Enrollment = require('../../models/Enrollment');
const auditService = require('../auditService');
const { AppError } = require('../../middleware/errorHandler');
const { toObjectId } = require('../../utils/objectId.util');
const crypto = require('crypto');
const { v4: uuidv4 } = require('uuid');

/** يتحقق أن المحاضر يملك الكورس فعلياً — نفس فحص الملكية المستخدم في COURSE */
async function assertInstructorOwnsCourse({ instructorId, courseId, req }) {
  const course = await Course.findById(courseId);
  if (!course) {
    throw new AppError(404, 'COURSE_NOT_FOUND', 'الكورس غير موجود.');
  }

  if (course.is_synchronous === false) {
    throw new AppError(
      400,
      'COURSE_IS_ASYNCHRONOUS',
      'لا يمكن إضافة جلسات مباشرة لكورس غير متزامن (Asynchronous).'
    );
  }

  if (course.owner_instructor_id.toString() !== instructorId.toString()) {
    await auditService.record({
      actorId: instructorId,
      actorRole: 'Instructor',
      action: 'UNAUTHORIZED_LIVE_SESSION_ACCESS_ATTEMPT',
      resourceType: 'Course',
      resourceId: courseId.toString(),
      metadata: { target_owner: course.owner_instructor_id },
      req,
    });
    throw new AppError(403, 'FORBIDDEN', 'لا تملك صلاحية إدارة جلسات هذا الكورس.');
  }

  if (['suspended', 'archived'].includes(course.status)) {
    throw new AppError(
      409,
      'COURSE_NOT_ACTIVE',
      `Cannot manage live sessions while course status is '${course.status}'.`
    );
  }

  return course;
}

async function assertUnitBelongsToCourseIfProvided({ unitId, courseId }) {
  if (!unitId) return null;
  const safeUnitId = toObjectId(unitId, 'unitId');
  const unit = await CourseUnit.findById(safeUnitId).lean();
  if (!unit || unit.course_id.toString() !== courseId.toString()) {
    throw new AppError(404, 'UNIT_NOT_FOUND', 'الوحدة غير موجودة ضمن هذا الكورس.');
  }
  return safeUnitId;
}

/** يتحقق أن المحاضر يملك الجلسة فعلياً، ويعيدها (وثيقة Mongoose قابلة للتعديل) */
async function assertInstructorOwnsSession({ instructorId, sessionId, req }) {
  const safeSessionId = toObjectId(sessionId, 'sessionId');
  const session = await LiveSession.findById(safeSessionId);
  if (!session) {
    throw new AppError(404, 'SESSION_NOT_FOUND', 'الجلسة غير موجودة.');
  }
  if (session.instructorId.toString() !== instructorId.toString()) {
    await auditService.record({
      actorId: instructorId,
      actorRole: 'Instructor',
      action: 'UNAUTHORIZED_LIVE_SESSION_ACCESS_ATTEMPT',
      resourceType: 'LiveSession',
      resourceId: safeSessionId.toString(),
      metadata: { target_owner: session.instructorId },
      req,
    });
    throw new AppError(403, 'FORBIDDEN', 'لا تملك صلاحية إدارة هذه الجلسة.');
  }
  return session;
}

/** يتحقق من وجود تعارض زمني مع جلسة أخرى لنفس الكورس (باستثناء الجلسة الحالية عند التعديل) */
async function findConflictingSession({ courseId, startTime, endTime, excludeSessionId = null }) {
  const query = {
    courseId,
    status: { $in: ['scheduled', 'ongoing'] },
    startTime: { $lt: endTime },
    endTime: { $gt: startTime },
  };
  if (excludeSessionId) {
    query._id = { $ne: excludeSessionId };
  }
  return LiveSession.findOne(query).lean();
}

/**
 * UC-LIVE-01 — Create/Schedule Session
 */
async function createSession({ instructorId, sessionData, req }) {
  const safeInstructorId = toObjectId(instructorId, 'instructorId');
  const safeCourseId = toObjectId(sessionData.courseId, 'courseId');

  await assertInstructorOwnsCourse({ instructorId: safeInstructorId, courseId: safeCourseId, req });

  const safeUnitId = await assertUnitBelongsToCourseIfProvided({
    unitId: sessionData.unit_id,
    courseId: safeCourseId,
  });

  const startTime = new Date(sessionData.startTime);
  const endTime = new Date(sessionData.endTime);
  const now = new Date();
  const moderatorPassword = crypto.randomBytes(8).toString('hex');

  if (startTime <= now) {
    throw new AppError(400, 'INVALID_START_TIME', 'يجب أن يكون وقت بدء الجلسة في المستقبل.');
  }
  if (endTime <= startTime) {
    throw new AppError(400, 'INVALID_TIME_RANGE', 'وقت النهاية يجب أن يكون بعد وقت البداية.');
  }

  const conflict = await findConflictingSession({ courseId: safeCourseId, startTime, endTime });
  if (conflict && !sessionData.confirmConflict) {
    throw new AppError(
      409,
      'SESSION_TIME_CONFLICT',
      'يوجد تعارض زمني مع جلسة أخرى لنفس الكورس. أرسل confirmConflict=true للمتابعة رغم ذلك.',
      { conflictingSessionId: conflict._id }
    );
  }

  const autoGeneratedRoom = `https://meet.jit.si/LMS-${uuidv4()}`;

  // Use the instructor's custom link if provided; otherwise, use the auto-generated link
  const finalMeetingLink = sessionData.meetingLink?.trim() || autoGeneratedRoom;

  const session = await LiveSession.create({
    courseId: safeCourseId,
    instructorId: safeInstructorId,
    unit_id: safeUnitId,
    title: sessionData.title,
    meetingLink: finalMeetingLink,
    moderatorPassword,
    startTime,
    endTime,
    lobbyEnabled: Boolean(sessionData.lobbyEnabled),
    status: 'scheduled',
  });

  await auditService.record({
    actorId: safeInstructorId,
    actorRole: 'Instructor',
    action: 'LIVE_SESSION_CREATED',
    resourceType: 'LiveSession',
    resourceId: session._id.toString(),
    metadata: { courseId: safeCourseId.toString(), startTime, endTime },
    req,
  });

  return { success: true, data: { session } };
}

/**
 * UC-LIVE-02 — Edit Session
 */
async function updateSession({ instructorId, sessionId, updateData, req }) {
  const safeInstructorId = toObjectId(instructorId, 'instructorId');
  const session = await assertInstructorOwnsSession({
    instructorId: safeInstructorId,
    sessionId,
    req,
  });

  if (session.status !== 'scheduled') {
    throw new AppError(
      400,
      'SESSION_NOT_EDITABLE',
      'لا يمكن تعديل جلسة بدأت بالفعل أو انتهت أو أُلغيت.'
    );
  }

  const nextStart = updateData.startTime ? new Date(updateData.startTime) : session.startTime;
  const nextEnd = updateData.endTime ? new Date(updateData.endTime) : session.endTime;

  if (nextEnd <= nextStart) {
    throw new AppError(400, 'INVALID_TIME_RANGE', 'وقت النهاية يجب أن يكون بعد وقت البداية.');
  }

  if (updateData.startTime || updateData.endTime) {
    const conflict = await findConflictingSession({
      courseId: session.courseId,
      startTime: nextStart,
      endTime: nextEnd,
      excludeSessionId: session._id,
    });
    if (conflict && !updateData.confirmConflict) {
      throw new AppError(
        409,
        'SESSION_TIME_CONFLICT',
        'يوجد تعارض زمني مع جلسة أخرى لنفس الكورس. أرسل confirmConflict=true للمتابعة رغم ذلك.',
        { conflictingSessionId: conflict._id }
      );
    }
  }

  const changedFields = {};
  ['title', 'meetingLink', 'lobbyEnabled'].forEach((field) => {
    if (updateData[field] !== undefined) {
      changedFields[field] = updateData[field];
      session[field] = updateData[field];
    }
  });
  if (updateData.startTime) {
    changedFields.startTime = nextStart;
    session.startTime = nextStart;
  }
  if (updateData.endTime) {
    changedFields.endTime = nextEnd;
    session.endTime = nextEnd;
  }

  if (updateData.unit_id !== undefined) {
    changedFields.unit_id = await assertUnitBelongsToCourseIfProvided({
      unitId: updateData.unit_id,
      courseId: session.courseId,
    });
    session.unit_id = changedFields.unit_id;
  }

  await session.save();

  await auditService.record({
    actorId: safeInstructorId,
    actorRole: 'Instructor',
    action: 'LIVE_SESSION_UPDATED',
    resourceType: 'LiveSession',
    resourceId: session._id.toString(),
    metadata: { changedFields },
    req,
  });

  // TODO(email): إشعار الطلاب المسجلين بالتعديل — يعيد استخدام نمط
  // sendLiveSessionScheduledNotification في emailService.js إن كانت موجودة
  // بنفس التوقيع المفترَض سابقاً (افتراض معلَّق من UC-LIVE-01 الأصلية).

  return { success: true, data: { session } };
}

/**
 * UC-LIVE-02 — Cancel Session
 */
async function cancelSession({ instructorId, sessionId, reason, req }) {
  const safeInstructorId = toObjectId(instructorId, 'instructorId');
  const session = await assertInstructorOwnsSession({
    instructorId: safeInstructorId,
    sessionId,
    req,
  });

  if (session.status === 'cancelled') {
    throw new AppError(400, 'ALREADY_CANCELLED', 'الجلسة ملغاة بالفعل.');
  }
  if (session.status === 'ended') {
    throw new AppError(400, 'SESSION_ALREADY_ENDED', 'لا يمكن إلغاء جلسة انتهت بالفعل.');
  }

  session.status = 'cancelled';
  session.cancelReason = reason || null;
  session.cancelledAt = new Date();
  await session.save();

  await auditService.record({
    actorId: safeInstructorId,
    actorRole: 'Instructor',
    action: 'LIVE_SESSION_CANCELLED',
    resourceType: 'LiveSession',
    resourceId: session._id.toString(),
    metadata: { reason: reason || null },
    req,
  });

  // TODO(email): إشعار الطلاب المسجلين بالإلغاء (نفس ملاحظة updateSession أعلاه)

  return { success: true, data: { session } };
}

// Fetch session with authorization
async function getSessionById({ userId, role, sessionId }) {
  const safeSessionId = toObjectId(sessionId, 'sessionId');
  let session = await LiveSession.findById(safeSessionId)
    .populate('instructorId', 'full_name email')
    .populate('courseId', 'title')
    .populate('unit_id', 'title')
    .lean();
  if (!session) throw new AppError(404, 'SESSION_NOT_FOUND');

  if (role === 'Instructor') {
    if (session.instructorId._id.toString() !== userId.toString()) {
      throw new AppError(403, 'FORBIDDEN', 'You do not own this session.');
    }
    const sessionWithPassword = await LiveSession.findById(safeSessionId)
      .select('+moderatorPassword')
      .lean();
    session.moderatorPassword = sessionWithPassword.moderatorPassword;
  } else {
    const enrolled = await Enrollment.findOne({
      student_id: userId,
      course_id: session.courseId,
      status: 'active',
    }).lean();
    if (!enrolled) {
      throw new AppError(403, 'NOT_ENROLLED', 'You are not enrolled in this course.');
    }
    delete session.moderatorPassword;
  }

  return { success: true, data: { session } };
}
/**
 * UC-LIVE-03 — View Live Schedule
 * الطالب: جلسات كورساته المسجَّل بها فقط (فحص خادمي عبر Enrollment، وليس ثقة بالعميل)
 * المحاضر: جلساته الخاصة فقط
 */
async function listSessionsForViewer({ userId, role, queryParams = {} }) {
  const safeUserId = toObjectId(userId, 'userId');
  const filter = {};

  if (
    queryParams.status &&
    ['scheduled', 'ongoing', 'ended', 'cancelled'].includes(queryParams.status)
  ) {
    filter.status = queryParams.status;
  }

  if (role === 'Instructor') {
    filter.instructorId = safeUserId;
  } else {
    const activeEnrollments = await Enrollment.find({ student_id: safeUserId, status: 'active' })
      .select('course_id')
      .lean();
    const courseIds = activeEnrollments.map((e) => e.course_id);
    if (courseIds.length === 0) {
      return { success: true, data: { sessions: [] } };
    }
    filter.courseId = { $in: courseIds };
  }

  const sessions = await LiveSession.find(filter)
    .populate('courseId', 'title')
    .populate('unit_id', 'title')
    .sort({ startTime: 1 })
    .lean();
  return { success: true, data: { sessions } };
}

async function startSession({ instructorId, sessionId, req }) {
  const safeInstructorId = toObjectId(instructorId, 'instructorId');
  const session = await assertInstructorOwnsSession({
    instructorId: safeInstructorId,
    sessionId,
    req,
  });

  if (session.status === 'ongoing')
    throw new AppError(400, 'ALREADY_STARTED', 'Session already started.');
  if (session.status === 'ended')
    throw new AppError(400, 'SESSION_ENDED', 'Session has already ended.');
  if (session.status === 'cancelled')
    throw new AppError(400, 'SESSION_CANCELLED', 'Session was cancelled.');

  session.status = 'ongoing';
  session.startedAt = new Date();
  session.studentsAllowed = false;
  await session.save();

  await auditService.record({
    actorId: safeInstructorId,
    actorRole: 'Instructor',
    action: 'LIVE_SESSION_STARTED',
    resourceType: 'LiveSession',
    resourceId: session._id.toString(),
    req,
  });

  return { success: true, data: { session } };
}

/**
 * UC-LIVE-08 — End Session
 */
async function endSession({ instructorId, sessionId, req }) {
  const safeInstructorId = toObjectId(instructorId, 'instructorId');
  const session = await assertInstructorOwnsSession({
    instructorId: safeInstructorId,
    sessionId,
    req,
  });

  if (session.status === 'ended') {
    throw new AppError(400, 'ALREADY_ENDED', 'الجلسة منتهية بالفعل.');
  }
  if (session.status === 'cancelled') {
    throw new AppError(400, 'SESSION_CANCELLED', 'لا يمكن إنهاء جلسة ملغاة.');
  }

  session.status = 'ended';
  session.endedAt = new Date();
  session.recordingStatus = 'processing';
  await session.save();

  await auditService.record({
    actorId: safeInstructorId,
    actorRole: 'Instructor',
    action: 'LIVE_SESSION_ENDED',
    resourceType: 'LiveSession',
    resourceId: session._id.toString(),
    metadata: {},
    req,
  });

  // إشعار أي طالب متصل حالياً بغرفة Jitsi بأن المحاضر أنهى المحاضرة فعلياً —
  // بنفس نمط toggleStudentsAccess (emitToSession)، حتى تُطرَد الواجهة فوراً
  // بدل ما يضل الطالب على شاشة بث مقطوعة بصمت.
  const { emitToSession } = require('../../sockets/liveSocketEmitter');
  emitToSession(session._id.toString(), 'session:ended', {});

  try {
    const { finalizeSessionAttendance } = require('../attendance/tracking.service');
    await finalizeSessionAttendance({ sessionId: session._id, req });
  } catch (err) {
    // eslint-disable-next-line no-console -- سيُستبدل بـ logger.js لاحقاً
    console.error('finalizeSessionAttendance failed (non-critical):', err.message);
  }

  try {
    const CourseProgressEvent = require('../../models/CourseProgressEvent');
    const Enrollment = require('../../models/Enrollment');
    const { getCompletionCounts, checkAndMarkCompletion } = require('../progress.service');

    const attendedStudentIds = await CourseProgressEvent.distinct('student_id', {
      session_id: session._id,
      source_type: 'live_session',
    });

    for (const studentId of attendedStudentIds) {
      const enrollment = await Enrollment.findOne({
        course_id: session.courseId,
        student_id: studentId,
        status: 'active',
      });
      if (!enrollment) continue; // ليس نشطاً (منسحب/مكتمل بالفعل) — لا شيء لفعله

      const { percentage } = await getCompletionCounts({
        courseId: session.courseId,
        studentId,
      });
      await checkAndMarkCompletion({
        enrollment,
        courseId: session.courseId,
        percentage,
        studentId,
      });
    }
  } catch (err) {
    // غير حرج: فشل إعادة فحص الاكتمال لا يجب أن يمنع إنهاء الجلسة نفسها
    // eslint-disable-next-line no-console -- سيُستبدل بـ logger.js لاحقاً
    console.error('Post-end completion re-check failed (non-critical):', err.message);
  }

  return { success: true, data: { session } };
}

async function toggleStudentsAccess({ instructorId, sessionId, allowed, req }) {
  const safeInstructorId = toObjectId(instructorId, 'instructorId');
  const session = await assertInstructorOwnsSession({
    instructorId: safeInstructorId,
    sessionId,
    req,
  });

  if (session.status !== 'ongoing') {
    throw new AppError(400, 'SESSION_NOT_ONGOING', 'يمكن فتح/قفل الدخول فقط أثناء بث الحصة.');
  }

  session.studentsAllowed = Boolean(allowed);
  await session.save();

  await auditService.record({
    actorId: safeInstructorId,
    actorRole: 'Instructor',
    action: session.studentsAllowed
      ? 'LIVE_SESSION_STUDENTS_UNLOCKED'
      : 'LIVE_SESSION_STUDENTS_LOCKED',
    resourceType: 'LiveSession',
    resourceId: session._id.toString(),
    metadata: {},
    req,
  });

  const { emitToSession } = require('../../sockets/liveSocketEmitter');
  emitToSession(session._id.toString(), 'students:access-changed', {
    allowed: session.studentsAllowed,
  });

  return { success: true, data: { session } };
}

/**
 * UC-LIVE-08 — Attach Recording (بعد اكتمال المعالجة/الرفع للسحابة خارجياً)
 * DEVIATION: رفع الفيديو الفعلي للسحابة خارج نطاق هذا التسليم — هذه الدالة
 * تُسجِّل فقط الرابط النهائي بعد اكتمال المعالجة (استدعاء لاحق يدوي من
 * المحاضر أو Webhook من خدمة المعالجة الخارجية).
 */
async function attachRecording({ instructorId, sessionId, recordingUrl, req }) {
  const safeInstructorId = toObjectId(instructorId, 'instructorId');
  const session = await assertInstructorOwnsSession({
    instructorId: safeInstructorId,
    sessionId,
    req,
  });

  if (session.status !== 'ended') {
    throw new AppError(400, 'SESSION_NOT_ENDED', 'يجب إنهاء الجلسة أولاً قبل إرفاق التسجيل.');
  }

  session.recordingUrl = recordingUrl;
  session.recordingStatus = 'ready';
  await session.save();

  await auditService.record({
    actorId: safeInstructorId,
    actorRole: 'Instructor',
    action: 'LIVE_SESSION_RECORDING_ATTACHED',
    resourceType: 'LiveSession',
    resourceId: session._id.toString(),
    metadata: { recordingUrl },
    req,
  });

  return { success: true, data: { session } };
}

/**
 * UC-LIVE — Participant Leaves Session
 *
 * Records the participant's departure without changing
 * the overall LiveSession status.
 */
async function leaveSession({ userId, role, sessionId, req }) {
  const safeUserId = toObjectId(userId, 'userId');
  const safeSessionId = toObjectId(sessionId, 'sessionId');

  const session = await LiveSession.findById(safeSessionId);

  if (!session) {
    throw new AppError(404, 'SESSION_NOT_FOUND', 'الجلسة غير موجودة.');
  }

  // Instructor must own the session.
  if (role === 'Instructor') {
    if (session.instructorId.toString() !== safeUserId.toString()) {
      throw new AppError(403, 'FORBIDDEN', 'لا تملك صلاحية هذه الجلسة.');
    }
  } else {
    // Student must be actively enrolled in the course.
    const enrolled = await Enrollment.findOne({
      student_id: safeUserId,
      course_id: session.courseId,
      status: 'active',
    }).lean();

    if (!enrolled) {
      throw new AppError(403, 'NOT_ENROLLED', 'أنت غير مسجل في هذا الكورس.');
    }
  }

  await auditService.record({
    actorId: safeUserId,
    actorRole: role,
    action: 'LIVE_SESSION_PARTICIPANT_LEFT',
    resourceType: 'LiveSession',
    resourceId: session._id.toString(),
    metadata: {},
    req,
  });

  return {
    success: true,
    data: {
      sessionId: session._id,
    },
  };
}

async function getLiveSessionsForUnit({ courseId, unitId }) {
  const safeCourseId = toObjectId(courseId, 'courseId');
  const safeUnitId = toObjectId(unitId, 'unitId');
  const sessions = await LiveSession.find({ courseId: safeCourseId, unit_id: safeUnitId })
    .select('title startTime endTime status')
    .sort({ startTime: 1 })
    .lean();
  return sessions.map((s) => ({
    session_id: s._id,
    title: s.title,
    scheduled_start: s.startTime,
    scheduled_end: s.endTime,
    status: s.status,
  }));
}

module.exports = {
  createSession,
  updateSession,
  cancelSession,
  listSessionsForViewer,
  startSession,
  endSession,
  leaveSession,
  attachRecording,
  assertInstructorOwnsSession,
  getSessionById,
  getLiveSessionsForUnit,
  assertUnitBelongsToCourseIfProvided,
  toggleStudentsAccess,
};
